# Generated by Django 4.0.1 on 2022-01-30 08:32

from django.db import migrations, models
import json.encoder


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Bill',
            field=models.JSONField(default=dict, encoder=json.encoder.JSONEncoder),
        ),
    ]
