# Generated by Django 4.0.1 on 2022-01-30 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Order_By',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
